# Generated by Django 5.1.1 on 2024-09-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
