# Generated by Django 5.1.1 on 2024-09-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_salary"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="salary",),
    ]
